import com.hill.planner.basic.Plane;
import org.joda.time.Interval;
import org.drools.planner.core.score.constraint.ConstraintType;
import org.drools.planner.core.score.constraint.IntConstraintOccurrence;
import org.drools.planner.core.score.buildin.hardandsoft.HardAndSoftScoreHolder;

global HardAndSoftScoreHolder scoreHolder;

rule "singlePlaneTaxiRule"
	when
		$plane : Plane($taxiInterval1 : taxiInterval, $id : id);
		$plane2 : Plane($taxiInterval2 : taxiInterval, id != $id);
	then
		int overlap = 0;
		if($taxiInterval1.overlap($taxiInterval2)!=null)
		{
			overlap = ((int)$taxiInterval1.overlap($taxiInterval2).toDurationMillis()/1000);
		}
		insertLogical(new IntConstraintOccurrence("singlePlaneTaxiRule", ConstraintType.NEGATIVE_HARD,
              			overlap,$plane,$plane2));	
end

//Potential vlaue pool is shared, need a hard constraint

rule "minimiseDelayRule"
	when
		$plane : Plane($tobt : tobt, $tsat : tsat != null);
	then
		//System.out.println("tobt "+$tobt + " tsat "+$tsat);
		
		long delay = (int) (new Interval($tobt, $tsat).toDurationMillis())/10000;

		insertLogical(new IntConstraintOccurrence("singlePlaneTaxiRule", ConstraintType.NEGATIVE_HARD,
              			delay,$plane));	
end


// Accumulate hard constraints
rule "hardConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $hardTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.NEGATIVE_HARD, $weight : weight),
            sum($weight)
        )
    then
        scoreHolder.setHardConstraintsBroken($hardTotal.intValue());
               			
        //System.out.println("H Score \t"+$hardTotal.intValue());
end

// Accumulate hard constraints
rule "softConstraintsBroken"
        salience -1 // Do the other rules first (optional, for performance)
    when
        $softTotal : Number() from accumulate(
            IntConstraintOccurrence(constraintType == ConstraintType.NEGATIVE_SOFT, $weight : weight),
            sum($weight)
        )
    then
        scoreHolder.setSoftConstraintsBroken($softTotal.intValue());
               			
        //System.out.println("S Score \t"+$softTotal.intValue());
end